name: example
description: A simple example app for the sliding_up_panel package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sliding_up_panel:
    path: ../

  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  #deprecated (Dart 3 incompatible)
  #latlong: ^0.6.1
  cached_network_image: ^3.3.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true